# SNS topic for operational alerts generated by CloudWatch alarms.
# This acts as the notification channel for Lab 1B incident response events.
resource "aws_sns_topic" "ops_alerts" {
  name = "${local.project_name}-ops-alerts"

  tags = merge(local.common_tags, {
    Name = "${local.project_name}-ops-alerts"
  })
}

# Email subscription for receiving operational alert notifications.
# I am using email here because it is easy to demonstrate and verify during testing.
resource "aws_sns_topic_subscription" "ops_email_subscription" {
  topic_arn = aws_sns_topic.ops_alerts.arn
  protocol  = "email"
  endpoint  = var.alert_email
}